### ISSUE TITLE
AWSIM feedback

### ISSUE THREAD

**Issue by WJaworskiRobotec** [autowarefoundation/AutowareProjects#67]
An issue to post the results / problems / suggestions for improvements/fixes of AWSIM

**Comment by xmfcx** [comment]
@TakaHoribe has tested it and made a post in here:
- https://github.com/orgs/autowarefoundation/discussions/3741#discussioncomment-6779568

I had made 3 tests.

## System & test setup

CPU: 5900X (12c24t)
GPU: RTX 3090 (24GB VRAM)
Memory: 64GB

I've used the commits:
- https://github.com/tier4/AWSIM/commit/d7d1d42a379b1996f4d00f21850e46074647fe21
   - (latest commit from last week)
   - Added https://assetstore.unity.com/packages/tools/gui/graphy-ultimate-fps-counter-stats-monitor-debugger-105778 to show the performance graphs
   - Enabled side lidars to have better perception performance (it worked with the launch file on autoware side without modifications)
   - Compiled a build because running from editor has worse performance.
- And latest autoware from with these frozen hashes:
<details>
  <summary>autoware-sim-test.repos</summary>

```yaml
repositories:
  core/autoware.core:
    type: git
    url: https://github.com/autowarefoundation/autoware.core.git
    version: 99891401473b5740e640f5a0cc0412c0984b8e0b
  core/autoware_adapi_msgs:
    type: git
    url: https://github.com/autowarefoundation/autoware_adapi_msgs.git
    version: fcdd3d07814b91090cd60079bd378396da6924de
  core/autoware_common:
    type: git
    url: https://github.com/autowarefoundation/autoware_common.git
    version: 58039c8b598d7e247994015d9c10c5b39e36b545
  core/autoware_msgs:
    type: git
    url: https://github.com/autowarefoundation/autoware_msgs.git
    version: 62f341d97515c81236a9a6700f02ca4e8df02304
  core/external/autoware_auto_msgs:
    type: git
    url: https://github.com/tier4/autoware_auto_msgs.git
    version: e1795354161ed54d66659366262578863bd2b862
  launcher/autoware_launch:
    type: git
    url: https://github.com/autowarefoundation/autoware_launch.git
    version: f5cd323f75dd8e5c9a210098970aa082b1be1a80
  middleware/external/heaphook:
    type: git
    url: https://github.com/tier4/heaphook.git
    version: ec260d7a7f06f29c04de2c846fa6d2158e770877
  param/autoware_individual_params:
    type: git
    url: https://github.com/autowarefoundation/autoware_individual_params.git
    version: 9b8b4064bf856dbd3f781a5ebd1f96135496878c
  sensor_component/external/nebula:
    type: git
    url: https://github.com/tier4/nebula.git
    version: 189d7e273aa66a528becac30024db5c96fa645b0
  sensor_component/external/sensor_component_description:
    type: git
    url: https://github.com/tier4/sensor_component_description.git
    version: a6a628186b124bc1af73c4f48a6dcd4b441391d3
  sensor_component/external/tamagawa_imu_driver:
    type: git
    url: https://github.com/tier4/tamagawa_imu_driver.git
    version: de4bf6be79aa2968cf2f62e0ebe1ff8a5797e6ad
  sensor_component/external/transport_drivers:
    type: git
    url: https://github.com/MapIV/transport_drivers.git
    version: d1e413482ca93c7618b005459a6a42e78e895442
  sensor_kit/external/awsim_sensor_kit_launch:
    type: git
    url: https://github.com/RobotecAI/awsim_sensor_kit_launch.git
    version: a1f5993407ffeb4abcf97a49cd1b4034768d97b4
  sensor_kit/sample_sensor_kit_launch:
    type: git
    url: https://github.com/autowarefoundation/sample_sensor_kit_launch.git
    version: 3cef1e4888a41001e4ebb3afbf63ae823e42e27d
  universe/autoware.universe:
    type: git
    url: https://github.com/autowarefoundation/autoware.universe.git
    version: e39c9282e259bab7f2342a736019ce07a9076377
  universe/external/eagleye:
    type: git
    url: https://github.com/MapIV/eagleye.git
    version: 82a4d060d622a426700f1bc83a3f265be5fa895a
  universe/external/llh_converter:
    type: git
    url: https://github.com/MapIV/llh_converter.git
    version: 07ad112b4f6b83eccd3a5f777bbe40ff01c67382
  universe/external/morai_msgs:
    type: git
    url: https://github.com/MORAI-Autonomous/MORAI-ROS2_morai_msgs.git
    version: 04f0a0b6a069fef62e0236189ce23d60abfe97f7
  universe/external/muSSP:
    type: git
    url: https://github.com/tier4/muSSP.git
    version: c79e98fd5e658f4f90c06d93472faa977bc873b9
  universe/external/ndt_omp:
    type: git
    url: https://github.com/tier4/ndt_omp.git
    version: 9a0877ac99cf873d9e984e4f1c485e537503fb7f
  universe/external/pointcloud_to_laserscan:
    type: git
    url: https://github.com/tier4/pointcloud_to_laserscan.git
    version: 948a4fca35dcb03c6c8fbfa610a686f7c919fe0b
  universe/external/rtklib_ros_bridge:
    type: git
    url: https://github.com/MapIV/rtklib_ros_bridge.git
    version: ef094407bba4f475a8032972e0c60cbb939b51b8
  universe/external/tier4_ad_api_adaptor:
    type: git
    url: https://github.com/tier4/tier4_ad_api_adaptor.git
    version: a58468edcdaf8698153c85e93fe23807edcb8187
  universe/external/tier4_autoware_msgs:
    type: git
    url: https://github.com/tier4/tier4_autoware_msgs.git
    version: fbc4871a7756bab7a99ba5ee0bd009861f2c67f3
  vehicle/external/pacmod_interface:
    type: git
    url: https://github.com/tier4/pacmod_interface.git
    version: 664a58db456e092659e5b25954fbf525593bf10d
  vehicle/sample_vehicle_launch:
    type: git
    url: https://github.com/autowarefoundation/sample_vehicle_launch.git
    version: 627068935b12ec6d6121e6a1b885e31d564b04c5
```
</details>

## Test details

- Both sim and autoware ran from the same computer.
- Because of this, the centerpoint neural net was competing for resources with AWSIM even though the GPU is very strong.
   - Also OBS was running to record at the same time, putting more load on gpu even though I've picked CPU encoding. When I move to separate pc, this will be eliminated too.
- Even then, the FPS in simulation wasn't that bad. (~9 FPS)
- **I will replicate the tests by running AWSIM in a separate PC that has an RTX 3080 with direct Ethernet connection.**
- I also didn't have traffic light recognition working. Probably need to tune the launch configuration for this.

### Test 1
- https://www.youtube.com/watch?v=QFD8jrXuS2Q
- Check the time tags in the video description for easy navigation in youtube

[0:50](https://www.youtube.com/watch?v=QFD8jrXuS2Q&t=50s) Test start
[0:57](https://www.youtube.com/watch?v=QFD8jrXuS2Q&t=57s) Random stop
[1:23](https://www.youtube.com/watch?v=QFD8jrXuS2Q&t=83s) Unable to turn
[2:18](https://www.youtube.com/watch?v=QFD8jrXuS2Q&t=138s) Random stop
[2:41](https://www.youtube.com/watch?v=QFD8jrXuS2Q&t=161s) End of test due to NPC traffic jam


### Test 2
- https://www.youtube.com/watch?v=NrlTcegIaCw
- Check the time tags in the video description for easy navigation in youtube

[1:38](https://www.youtube.com/watch?v=NrlTcegIaCw&t=98s) Test start
[2:04](https://www.youtube.com/watch?v=NrlTcegIaCw&t=124s) Random stop
[2:14](https://www.youtube.com/watch?v=NrlTcegIaCw&t=134s) Random stop
[2:29](https://www.youtube.com/watch?v=NrlTcegIaCw&t=149s) Attempts to change lane, stops unexpectedly
[2:56](https://www.youtube.com/watch?v=NrlTcegIaCw&t=176s) Fails to go back to the old lane
[3:07](https://www.youtube.com/watch?v=NrlTcegIaCw&t=187s) Stuck waiting in the middle of the road
[3:52](https://www.youtube.com/watch?v=NrlTcegIaCw&t=232s) Stuck in the middle of the road without anything blocking the path


### Test 3
- https://www.youtube.com/watch?v=N3LyPfmPuDI
- Check the time tags in the video description for easy navigation in youtube

[1:08](https://www.youtube.com/watch?v=N3LyPfmPuDI&t=68s) Test start
[1:19](https://www.youtube.com/watch?v=N3LyPfmPuDI&t=79s) Crashes to obviously incoming vehicle from right and stops after it happens
[1:24](https://www.youtube.com/watch?v=N3LyPfmPuDI&t=84s) Stops before vehicle in front and keeps blocking the road
[2:10](https://www.youtube.com/watch?v=N3LyPfmPuDI&t=130s) fails to turn the empty road curve
[2:20](https://www.youtube.com/watch?v=N3LyPfmPuDI&t=140s) fails to turn the empty road curve
[2:45](https://www.youtube.com/watch?v=N3LyPfmPuDI&t=165s) waits too long in walkway
[3:17](https://www.youtube.com/watch?v=N3LyPfmPuDI&t=197s) stuck in narrow node


cc. @mehmetdogru @WJaworskiRobotec @armaganarsln @yukkysaito
